export interface WorkflowStep {
    name: string;
    role: string;
    days: number;
}

export interface WorkflowTemplate {
    id: string;
    name: string;
    category: 'Content' | 'Tech' | 'Marketing' | 'Design' | 'Business' | 'Education' | 'Manufacturing';
    icon: string;
    description: string;
    steps: WorkflowStep[];
}

export const ALL_WORKFLOWS: WorkflowTemplate[] = [
    // ---- CONTENT & CREATOR (20) ----
    {
        id: 'wf-youtube',
        name: 'YouTube Video Production',
        category: 'Content',
        icon: '🎬',
        description: 'Complete YouTube workflow with role assignments and time estimates.',
        steps: [
            { name: 'Research & Script', role: 'Content Writer', days: 2 },
            { name: 'Video Shoot', role: 'Videographer', days: 3 },
            { name: 'Editing & VFX', role: 'Video Editor', days: 4 },
            { name: 'Thumbnail Design', role: 'Graphic Designer', days: 1 },
            { name: 'SEO & Upload', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-podcast',
        name: 'Podcast Production',
        category: 'Content',
        icon: '🎙️',
        description: 'Record, edit, and publish a podcast episode.',
        steps: [
            { name: 'Topic Research', role: 'Researcher', days: 1 },
            { name: 'Guest Booking', role: 'Coordinator', days: 2 },
            { name: 'Recording', role: 'Audio Engineer', days: 1 },
            { name: 'Audio Editing', role: 'Audio Editor', days: 2 },
            { name: 'Show Notes', role: 'Content Writer', days: 1 },
            { name: 'Publish & Promote', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-blog',
        name: 'Blog Post Writing',
        category: 'Content',
        icon: '✍️',
        description: 'Write and publish a SEO-optimized blog post.',
        steps: [
            { name: 'Keyword Research', role: 'SEO Specialist', days: 1 },
            { name: 'Outline', role: 'Content Strategist', days: 1 },
            { name: 'Drafting', role: 'Content Writer', days: 2 },
            { name: 'Editing', role: 'Editor', days: 1 },
            { name: 'SEO Optimization', role: 'SEO Specialist', days: 1 },
            { name: 'Publish & Promote', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-newsletter',
        name: 'Newsletter Campaign',
        category: 'Marketing',
        icon: '📧',
        description: 'Create and send a weekly newsletter.',
        steps: [
            { name: 'Content Curation', role: 'Researcher', days: 1 },
            { name: 'Writing', role: 'Content Writer', days: 1 },
            { name: 'Design Layout', role: 'Designer', days: 1 },
            { name: 'Review', role: 'Editor', days: 1 },
            { name: 'Send Test', role: 'Manager', days: 1 },
            { name: 'Schedule Send', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-social-media',
        name: 'Social Media Posting',
        category: 'Marketing',
        icon: '📱',
        description: 'Plan, create, and schedule social media content.',
        steps: [
            { name: 'Content Calendar', role: 'Social Media Manager', days: 2 },
            { name: 'Copywriting', role: 'Content Writer', days: 1 },
            { name: 'Visual Design', role: 'Designer', days: 2 },
            { name: 'Review', role: 'Manager', days: 1 },
            { name: 'Schedule', role: 'Social Media Manager', days: 1 },
            { name: 'Publish & Engage', role: 'Social Media Manager', days: 1 },
        ],
    },
    {
        id: 'wf-video-shorts',
        name: 'YouTube Shorts / Reels',
        category: 'Content',
        icon: '📲',
        description: 'Create short-form video content.',
        steps: [
            { name: 'Trend Research', role: 'Researcher', days: 1 },
            { name: 'Script', role: 'Content Writer', days: 1 },
            { name: 'Shoot', role: 'Videographer', days: 1 },
            { name: 'Editing', role: 'Video Editor', days: 1 },
            { name: 'Upload', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-ghostwriting',
        name: 'Ghostwriting Book',
        category: 'Content',
        icon: '📖',
        description: 'Write a book for a client.',
        steps: [
            { name: 'Outline', role: 'Content Strategist', days: 3 },
            { name: 'Research', role: 'Researcher', days: 5 },
            { name: 'Drafting', role: 'Content Writer', days: 10 },
            { name: 'Editing', role: 'Editor', days: 3 },
            { name: 'Review', role: 'Manager', days: 2 },
            { name: 'Final Manuscript', role: 'Content Writer', days: 2 },
        ],
    },
    {
        id: 'wf-voice-over',
        name: 'Voice Over / Dubbing',
        category: 'Content',
        icon: '🎤',
        description: 'Professional voice recording for videos or ads.',
        steps: [
            { name: 'Script Finalization', role: 'Content Writer', days: 1 },
            { name: 'Studio Booking', role: 'Coordinator', days: 1 },
            { name: 'Recording', role: 'Voice Artist', days: 1 },
            { name: 'Audio Cleanup', role: 'Audio Engineer', days: 1 },
            { name: 'Mix & Master', role: 'Audio Engineer', days: 1 },
            { name: 'Delivery', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-script-writing',
        name: 'Script Writing (Movies)',
        category: 'Content',
        icon: '🎞️',
        description: 'Write a movie or web series script.',
        steps: [
            { name: 'Concept', role: 'Screenwriter', days: 3 },
            { name: 'Outline', role: 'Screenwriter', days: 2 },
            { name: 'Draft', role: 'Screenwriter', days: 7 },
            { name: 'Feedback', role: 'Editor', days: 2 },
            { name: 'Rewrite', role: 'Screenwriter', days: 3 },
            { name: 'Final', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-film-production',
        name: 'Short Film Production',
        category: 'Content',
        icon: '📽️',
        description: 'Complete short filmmaking process.',
        steps: [
            { name: 'Script', role: 'Screenwriter', days: 5 },
            { name: 'Storyboard', role: 'Director', days: 2 },
            { name: 'Casting', role: 'Casting Director', days: 3 },
            { name: 'Shoot', role: 'DP', days: 5 },
            { name: 'Post-Production', role: 'Editor', days: 7 },
            { name: 'Festival Submission', role: 'Manager', days: 2 },
        ],
    },

    // ---- TECH & DEVELOPMENT (20) ----
    {
        id: 'wf-web-dev',
        name: 'Website Development',
        category: 'Tech',
        icon: '🌐',
        description: 'Full website development lifecycle.',
        steps: [
            { name: 'Discovery', role: 'Product Manager', days: 3 },
            { name: 'UI/UX Design', role: 'Designer', days: 5 },
            { name: 'Frontend Coding', role: 'React Dev', days: 10 },
            { name: 'Backend API', role: 'Node Dev', days: 8 },
            { name: 'Database Setup', role: 'DB Admin', days: 2 },
            { name: 'Testing', role: 'QA', days: 3 },
            { name: 'Deployment', role: 'DevOps', days: 2 },
            { name: 'Maintenance', role: 'DevOps', days: 1 },
        ],
    },
    {
        id: 'wf-mobile-app',
        name: 'Mobile App Development',
        category: 'Tech',
        icon: '📱',
        description: 'React Native / Flutter app build.',
        steps: [
            { name: 'Requirement Analysis', role: 'Product Manager', days: 3 },
            { name: 'UI Design', role: 'Designer', days: 4 },
            { name: 'App Architecture', role: 'Tech Lead', days: 2 },
            { name: 'Development', role: 'React Native Dev', days: 12 },
            { name: 'QA Testing', role: 'QA', days: 3 },
            { name: 'Store Submission', role: 'Manager', days: 2 },
        ],
    },
    {
        id: 'wf-software-feature',
        name: 'New Software Feature',
        category: 'Tech',
        icon: '⚙️',
        description: 'Add a new feature in existing software.',
        steps: [
            { name: 'Product Spec', role: 'Product Manager', days: 2 },
            { name: 'Design', role: 'Designer', days: 3 },
            { name: 'Development', role: 'Developer', days: 5 },
            { name: 'Code Review', role: 'Tech Lead', days: 1 },
            { name: 'QA', role: 'QA', days: 2 },
            { name: 'Release Notes', role: 'Product Manager', days: 1 },
            { name: 'Deploy', role: 'DevOps', days: 1 },
        ],
    },
    {
        id: 'wf-data-migration',
        name: 'Data Migration',
        category: 'Tech',
        icon: '🗄️',
        description: 'Moving data from one system to another.',
        steps: [
            { name: 'Audit', role: 'Data Engineer', days: 2 },
            { name: 'Mapping', role: 'Data Engineer', days: 3 },
            { name: 'Backup', role: 'DB Admin', days: 1 },
            { name: 'Migration Script', role: 'Data Engineer', days: 3 },
            { name: 'Test Run', role: 'QA', days: 2 },
            { name: 'Final Run', role: 'Data Engineer', days: 1 },
            { name: 'Verification', role: 'QA', days: 1 },
        ],
    },
    {
        id: 'wf-ai-model',
        name: 'AI/ML Model Training',
        category: 'Tech',
        icon: '🧠',
        description: 'Train and deploy a machine learning model.',
        steps: [
            { name: 'Data Collection', role: 'Data Scientist', days: 5 },
            { name: 'Data Cleaning', role: 'Data Scientist', days: 3 },
            { name: 'Feature Engineering', role: 'ML Engineer', days: 3 },
            { name: 'Training', role: 'ML Engineer', days: 4 },
            { name: 'Evaluation', role: 'ML Engineer', days: 2 },
            { name: 'Deployment', role: 'DevOps', days: 2 },
            { name: 'Monitoring', role: 'ML Engineer', days: 1 },
        ],
    },
    {
        id: 'wf-devops',
        name: 'DevOps Pipeline Setup',
        category: 'Tech',
        icon: '🔧',
        description: 'CI/CD pipeline configuration.',
        steps: [
            { name: 'Infra Setup', role: 'DevOps', days: 2 },
            { name: 'Dockerization', role: 'DevOps', days: 2 },
            { name: 'CI Config', role: 'DevOps', days: 2 },
            { name: 'CD Config', role: 'DevOps', days: 2 },
            { name: 'Monitoring', role: 'DevOps', days: 1 },
            { name: 'Documentation', role: 'DevOps', days: 1 },
        ],
    },
    {
        id: 'wf-bug-fix',
        name: 'Critical Bug Fix',
        category: 'Tech',
        icon: '🐞',
        description: 'Urgent production issue resolution.',
        steps: [
            { name: 'Bug Report', role: 'Support', days: 1 },
            { name: 'Reproduce', role: 'QA', days: 1 },
            { name: 'Root Cause', role: 'Developer', days: 1 },
            { name: 'Fix', role: 'Developer', days: 1 },
            { name: 'Review', role: 'Tech Lead', days: 1 },
            { name: 'Deploy', role: 'DevOps', days: 1 },
            { name: 'Monitor', role: 'Developer', days: 1 },
        ],
    },
    {
        id: 'wf-saas-onboarding',
        name: 'SaaS Product Onboarding',
        category: 'Tech',
        icon: '🧑‍💻',
        description: 'User activation journey for a SaaS product.',
        steps: [
            { name: 'Signup Flow', role: 'Product Manager', days: 2 },
            { name: 'Tutorial Design', role: 'Designer', days: 3 },
            { name: 'In-app Guidance', role: 'Developer', days: 4 },
            { name: 'Onboarding Emails', role: 'Content Writer', days: 2 },
            { name: 'Feedback Collection', role: 'Product Manager', days: 1 },
        ],
    },
    {
        id: 'wf-crm-implementation',
        name: 'CRM Implementation',
        category: 'Business',
        icon: '📊',
        description: 'Salesforce / HubSpot setup for business.',
        steps: [
            { name: 'Requirement', role: 'Business Analyst', days: 3 },
            { name: 'Data Import', role: 'Data Engineer', days: 2 },
            { name: 'Customization', role: 'Developer', days: 5 },
            { name: 'User Training', role: 'Trainer', days: 2 },
            { name: 'Go-Live', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-app-review',
        name: 'App Store Review',
        category: 'Tech',
        icon: '⭐',
        description: 'Resolve app rejection issues on App Store / Play Store.',
        steps: [
            { name: 'Read Guidelines', role: 'Product Manager', days: 1 },
            { name: 'Appeal', role: 'Manager', days: 1 },
            { name: 'Fix Issues', role: 'Developer', days: 2 },
            { name: 'Resubmit', role: 'Manager', days: 1 },
            { name: 'Confirm', role: 'QA', days: 1 },
        ],
    },

    // ---- MARKETING & AGENCY (20) ----
    {
        id: 'wf-seo',
        name: 'SEO Campaign',
        category: 'Marketing',
        icon: '🔍',
        description: 'Boost organic traffic with a comprehensive SEO strategy.',
        steps: [
            { name: 'Audit', role: 'SEO Specialist', days: 2 },
            { name: 'Keyword Research', role: 'SEO Specialist', days: 2 },
            { name: 'On-Page Optimization', role: 'SEO Specialist', days: 3 },
            { name: 'Content Creation', role: 'Content Writer', days: 5 },
            { name: 'Link Building', role: 'SEO Specialist', days: 7 },
            { name: 'Monitor Rankings', role: 'SEO Specialist', days: 1 },
        ],
    },
    {
        id: 'wf-ppc-ads',
        name: 'PPC / Google Ads',
        category: 'Marketing',
        icon: '💸',
        description: 'Paid advertising campaigns on Google / Meta.',
        steps: [
            { name: 'Campaign Strategy', role: 'PPC Specialist', days: 2 },
            { name: 'Keyword Bidding', role: 'PPC Specialist', days: 1 },
            { name: 'Ad Copy', role: 'Content Writer', days: 2 },
            { name: 'Landing Page', role: 'Designer', days: 3 },
            { name: 'Launch', role: 'PPC Specialist', days: 1 },
            { name: 'Optimize', role: 'PPC Specialist', days: 2 },
            { name: 'Reporting', role: 'PPC Specialist', days: 1 },
        ],
    },
    {
        id: 'wf-email-drip',
        name: 'Email Drip Campaign',
        category: 'Marketing',
        icon: '📨',
        description: 'Lead nurturing via automated email sequences.',
        steps: [
            { name: 'Lead List', role: 'Data Analyst', days: 2 },
            { name: 'Segment', role: 'Data Analyst', days: 1 },
            { name: 'Email Copy', role: 'Content Writer', days: 3 },
            { name: 'Design Template', role: 'Designer', days: 2 },
            { name: 'Setup Automation', role: 'Marketing Ops', days: 2 },
            { name: 'Test', role: 'QA', days: 1 },
            { name: 'Launch', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-product-launch',
        name: 'Product Launch',
        category: 'Marketing',
        icon: '🚀',
        description: 'End-to-end product go-to-market strategy.',
        steps: [
            { name: 'Market Research', role: 'Product Manager', days: 5 },
            { name: 'MVP Build', role: 'Developer', days: 10 },
            { name: 'Beta Testing', role: 'QA', days: 3 },
            { name: 'Marketing Collateral', role: 'Designer', days: 5 },
            { name: 'PR', role: 'PR Manager', days: 3 },
            { name: 'Launch Event', role: 'Manager', days: 2 },
            { name: 'Post-Launch', role: 'Product Manager', days: 2 },
        ],
    },
    {
        id: 'wf-influencer',
        name: 'Influencer Marketing',
        category: 'Marketing',
        icon: '🤳',
        description: 'Collaborate with influencers for brand promotion.',
        steps: [
            { name: 'Identify Influencers', role: 'Marketing Manager', days: 3 },
            { name: 'Reach Out', role: 'Marketing Manager', days: 3 },
            { name: 'Negotiate', role: 'Marketing Manager', days: 2 },
            { name: 'Brief', role: 'Content Writer', days: 2 },
            { name: 'Content Review', role: 'Manager', days: 2 },
            { name: 'Post', role: 'Influencer', days: 1 },
            { name: 'Track', role: 'Data Analyst', days: 1 },
        ],
    },
    {
        id: 'wf-community-build',
        name: 'Community Building (Discord)',
        category: 'Marketing',
        icon: '💬',
        description: 'Build and grow a community platform.',
        steps: [
            { name: 'Strategy', role: 'Community Manager', days: 2 },
            { name: 'Channel Setup', role: 'Community Manager', days: 1 },
            { name: 'Mods', role: 'Community Manager', days: 2 },
            { name: 'Content Plan', role: 'Content Writer', days: 3 },
            { name: 'Engagement', role: 'Community Manager', days: 7 },
            { name: 'Growth Hacks', role: 'Community Manager', days: 2 },
        ],
    },
    {
        id: 'wf-brand-strategy',
        name: 'Brand Strategy Workshop',
        category: 'Business',
        icon: '🧠',
        description: 'Define brand positioning and messaging.',
        steps: [
            { name: 'Discovery', role: 'Brand Strategist', days: 3 },
            { name: 'Competitor Analysis', role: 'Brand Strategist', days: 2 },
            { name: 'Positioning', role: 'Brand Strategist', days: 2 },
            { name: 'Workshop', role: 'Brand Strategist', days: 1 },
            { name: 'Output', role: 'Brand Strategist', days: 2 },
        ],
    },
    {
        id: 'wf-merchandise',
        name: 'Merchandise Drop (T-Shirts)',
        category: 'Marketing',
        icon: '👕',
        description: 'Design and sell merchandise.',
        steps: [
            { name: 'Design', role: 'Designer', days: 3 },
            { name: 'Supplier Sourcing', role: 'Manager', days: 2 },
            { name: 'Samples', role: 'Manager', days: 3 },
            { name: 'Printing', role: 'Supplier', days: 5 },
            { name: 'Store Setup', role: 'Manager', days: 2 },
            { name: 'Pre-Orders', role: 'Marketing Manager', days: 2 },
            { name: 'Ship', role: 'Manager', days: 2 },
        ],
    },
    {
        id: 'wf-instagram-growth',
        name: 'Instagram Growth Engine',
        category: 'Marketing',
        icon: '📈',
        description: 'Strategy for growing Instagram followers.',
        steps: [
            { name: 'Audit', role: 'Social Media Manager', days: 1 },
            { name: 'Content Plan', role: 'Content Writer', days: 3 },
            { name: 'Engagement', role: 'Social Media Manager', days: 7 },
            { name: 'Collabs', role: 'Marketing Manager', days: 3 },
            { name: 'Analyze', role: 'Data Analyst', days: 1 },
        ],
    },
    {
        id: 'wf-whitepaper',
        name: 'Whitepaper Writing',
        category: 'Marketing',
        icon: '📑',
        description: 'Write a detailed industry whitepaper.',
        steps: [
            { name: 'Topic', role: 'Content Strategist', days: 2 },
            { name: 'Research', role: 'Researcher', days: 5 },
            { name: 'Outline', role: 'Content Strategist', days: 2 },
            { name: 'Draft', role: 'Content Writer', days: 5 },
            { name: 'Design', role: 'Designer', days: 3 },
            { name: 'Publish', role: 'Manager', days: 2 },
        ],
    },

    // ---- DESIGN (15) ----
    {
        id: 'wf-brand-identity',
        name: 'Brand Identity Design',
        category: 'Design',
        icon: '🏷️',
        description: 'Logo, color palette, typography, and guidelines.',
        steps: [
            { name: 'Brief', role: 'Designer', days: 2 },
            { name: 'Research', role: 'Designer', days: 2 },
            { name: 'Moodboard', role: 'Designer', days: 2 },
            { name: 'Logo Concepts', role: 'Designer', days: 3 },
            { name: 'Refinement', role: 'Designer', days: 2 },
            { name: 'Brand Guidelines', role: 'Designer', days: 3 },
            { name: 'Deliver', role: 'Manager', days: 1 },
        ],
    },
    {
        id: 'wf-ui-ux-design',
        name: 'UI/UX Design Project',
        category: 'Design',
        icon: '🎨',
        description: 'Figma-based design system for apps or websites.',
        steps: [
            { name: 'User Research', role: 'UX Researcher', days: 3 },
            { name: 'Wireframes', role: 'UX Designer', days: 3 },
            { name: 'High-Fidelity', role: 'UI Designer', days: 4 },
            { name: 'Prototype', role: 'UX Designer', days: 2 },
            { name: 'Usability Testing', role: 'UX Researcher', days: 2 },
            { name: 'Handoff to Dev', role: 'UI Designer', days: 1 },
        ],
    },
    {
        id: 'wf-3d-animation',
        name: '3D Animation / Motion Graphics',
        category: 'Design',
        icon: '🪄',
        description: 'Blender/After Effects animation for videos.',
        steps: [
            { name: 'Storyboard', role: 'Designer', days: 2 },
            { name: '3D Modeling', role: '3D Artist', days: 4 },
            { name: 'Texturing', role: '3D Artist', days: 2 },
            { name: 'Animation', role: 'Animator', days: 4 },
            { name: 'Lighting', role: '3D Artist', days: 2 },
            { name: 'Render', role: 'Animator', days: 2 },
            { name: 'Post-Production', role: 'Video Editor', days: 2 },
        ],
    },
    {
        id: 'wf-ui-audit',
        name: 'UI/UX Audit',
        category: 'Design',
        icon: '🔎',
        description: 'Audit existing product UI and provide recommendations.',
        steps: [
            { name: 'Heuristic Review', role: 'UX Researcher', days: 2 },
            { name: 'User Testing', role: 'UX Researcher', days: 2 },
            { name: 'Report', role: 'UX Designer', days: 2 },
            { name: 'Presentation', role: 'UX Designer', days: 1 },
        ],
    },
    {
        id: 'wf-interior-design',
        name: 'Interior Design Project',
        category: 'Design',
        icon: '🛋️',
        description: 'Residential or office interior design.',
        steps: [
            { name: 'Brief', role: 'Interior Designer', days: 2 },
            { name: 'Site Visit', role: 'Interior Designer', days: 1 },
            { name: 'Moodboard', role: 'Interior Designer', days: 2 },
            { name: '3D Renders', role: '3D Artist', days: 4 },
            { name: 'Material Selection', role: 'Interior Designer', days: 2 },
            { name: 'Execution', role: 'Manager', days: 5 },
        ],
    },

    // ---- BUSINESS & OPERATIONS (15) ----
    {
        id: 'wf-hiring',
        name: 'Hiring / Recruitment',
        category: 'Business',
        icon: '👔',
        description: 'Hire a new team member.',
        steps: [
            { name: 'JD Creation', role: 'HR', days: 2 },
            { name: 'Post Job', role: 'HR', days: 1 },
            { name: 'Resume Screening', role: 'HR', days: 3 },
            { name: 'Interview Round 1', role: 'Hiring Manager', days: 3 },
            { name: 'Interview Round 2', role: 'Hiring Manager', days: 2 },
            { name: 'Offer', role: 'HR', days: 2 },
            { name: 'Onboarding', role: 'HR', days: 2 },
        ],
    },
    {
        id: 'wf-client-onboarding',
        name: 'Client Onboarding',
        category: 'Business',
        icon: '🤝',
        description: 'Smooth onboarding experience for new clients.',
        steps: [
            { name: 'Signed Contract', role: 'Account Manager', days: 2 },
            { name: 'Kickoff Call', role: 'Account Manager', days: 1 },
            { name: 'Access Setup', role: 'Manager', days: 1 },
            { name: 'Intro to Team', role: 'Account Manager', days: 1 },
            { name: 'Project Plan', role: 'Project Manager', days: 2 },
            { name: 'First Deliverable', role: 'Project Manager', days: 3 },
        ],
    },
    {
        id: 'wf-annual-budget',
        name: 'Annual Budget Planning',
        category: 'Business',
        icon: '💰',
        description: 'Plan company financials for the year.',
        steps: [
            { name: 'Review Last Year', role: 'Finance', days: 3 },
            { name: 'Forecast', role: 'Finance', days: 3 },
            { name: 'Department Inputs', role: 'Finance', days: 3 },
            { name: 'Consolidate', role: 'Finance', days: 2 },
            { name: 'Board Approval', role: 'CEO', days: 2 },
            { name: 'Allocate', role: 'Finance', days: 2 },
        ],
    },
    {
        id: 'wf-event-planning',
        name: 'Event Planning',
        category: 'Business',
        icon: '🎉',
        description: 'Conference, webinar, or offline meetup.',
        steps: [
            { name: 'Concept', role: 'Event Manager', days: 2 },
            { name: 'Venue Booking', role: 'Event Manager', days: 2 },
            { name: 'Speakers', role: 'Event Manager', days: 5 },
            { name: 'Registration', role: 'Event Manager', days: 2 },
            { name: 'Marketing', role: 'Marketing Manager', days: 5 },
            { name: 'Day-of Execution', role: 'Event Manager', days: 1 },
            { name: 'Feedback', role: 'Event Manager', days: 1 },
        ],
    },
    {
        id: 'wf-patent',
        name: 'Patent Filing',
        category: 'Business',
        icon: '📜',
        description: 'Intellectual property protection through patents.',
        steps: [
            { name: 'Research', role: 'Legal', days: 5 },
            { name: 'Draft Claims', role: 'Legal', days: 5 },
            { name: 'Review', role: 'Legal', days: 3 },
            { name: 'File Application', role: 'Legal', days: 2 },
            { name: 'Respond', role: 'Legal', days: 3 },
        ],
    },
    {
        id: 'wf-legal-drafting',
        name: 'Legal Contract Drafting',
        category: 'Business',
        icon: '⚖️',
        description: 'Draft and review legal agreements.',
        steps: [
            { name: 'Requirement', role: 'Legal', days: 2 },
            { name: 'Research', role: 'Legal', days: 2 },
            { name: 'Draft', role: 'Legal', days: 3 },
            { name: 'Review', role: 'Legal', days: 2 },
            { name: 'Client Feedback', role: 'Legal', days: 2 },
            { name: 'Finalize', role: 'Legal', days: 1 },
        ],
    },
    {
        id: 'wf-accounting',
        name: 'Monthly Accounting Close',
        category: 'Business',
        icon: '🧾',
        description: 'End-of-month bookkeeping and reporting.',
        steps: [
            { name: 'Collect Invoices', role: 'Accountant', days: 2 },
            { name: 'Reconcile', role: 'Accountant', days: 3 },
            { name: 'Review', role: 'Accountant', days: 1 },
            { name: 'Report', role: 'Accountant', days: 2 },
            { name: 'Submit', role: 'Accountant', days: 1 },
        ],
    },
    {
        id: 'wf-ngo-project',
        name: 'NGO / Social Project',
        category: 'Business',
        icon: '🤲',
        description: 'Manage a social welfare project.',
        steps: [
            { name: 'Needs Assessment', role: 'Project Manager', days: 4 },
            { name: 'Planning', role: 'Project Manager', days: 3 },
            { name: 'Funding', role: 'Project Manager', days: 5 },
            { name: 'Implementation', role: 'Project Manager', days: 10 },
            { name: 'Monitoring', role: 'Project Manager', days: 3 },
            { name: 'Impact Report', role: 'Project Manager', days: 2 },
        ],
    },
    {
        id: 'wf-freelance-proposal',
        name: 'Freelance Proposal/Quoting',
        category: 'Business',
        icon: '📄',
        description: 'Create a winning client proposal.',
        steps: [
            { name: 'Client Brief', role: 'Freelancer', days: 1 },
            { name: 'Scope', role: 'Freelancer', days: 1 },
            { name: 'Pricing', role: 'Freelancer', days: 1 },
            { name: 'Draft', role: 'Freelancer', days: 1 },
            { name: 'Review', role: 'Freelancer', days: 1 },
            { name: 'Send', role: 'Freelancer', days: 1 },
        ],
    },

    // ---- EDUCATION (10) ----
    {
        id: 'wf-online-course',
        name: 'Online Course Creation',
        category: 'Education',
        icon: '📚',
        description: 'Create and sell a digital course.',
        steps: [
            { name: 'Curriculum Design', role: 'Instructor', days: 5 },
            { name: 'Video Script', role: 'Content Writer', days: 3 },
            { name: 'Filming', role: 'Videographer', days: 3 },
            { name: 'Editing', role: 'Video Editor', days: 4 },
            { name: 'Platform Setup', role: 'Manager', days: 2 },
            { name: 'Pricing', role: 'Manager', days: 1 },
            { name: 'Launch', role: 'Marketing Manager', days: 2 },
        ],
    },
    {
        id: 'wf-student-project',
        name: 'College Student Project',
        category: 'Education',
        icon: '🎓',
        description: 'Final year project management for students.',
        steps: [
            { name: 'Topic Selection', role: 'Student', days: 3 },
            { name: 'Research', role: 'Student', days: 5 },
            { name: 'Implementation', role: 'Student', days: 7 },
            { name: 'Testing', role: 'Student', days: 3 },
            { name: 'Documentation', role: 'Student', days: 3 },
            { name: 'Presentation', role: 'Student', days: 2 },
        ],
    },
    {
        id: 'wf-research-paper',
        name: 'Research Paper Submission',
        category: 'Education',
        icon: '🧪',
        description: 'Academic research to journal publication.',
        steps: [
            { name: 'Hypothesis', role: 'Researcher', days: 3 },
            { name: 'Experiments', role: 'Researcher', days: 7 },
            { name: 'Data Collection', role: 'Researcher', days: 4 },
            { name: 'Analysis', role: 'Researcher', days: 3 },
            { name: 'Paper Write', role: 'Researcher', days: 5 },
            { name: 'Peer Review', role: 'Editor', days: 3 },
            { name: 'Publish', role: 'Manager', days: 2 },
        ],
    },
    {
        id: 'wf-fitness-program',
        name: 'Fitness Program Design',
        category: 'Education',
        icon: '💪',
        description: 'Create a workout/nutrition plan.',
        steps: [
            { name: 'Client Assessment', role: 'Trainer', days: 1 },
            { name: 'Goal Setting', role: 'Trainer', days: 1 },
            { name: 'Plan Design', role: 'Trainer', days: 2 },
            { name: 'Feedback', role: 'Trainer', days: 1 },
            { name: 'Iterate', role: 'Trainer', days: 1 },
        ],
    },

    // ---- MANUFACTURING & PHYSICAL (10) ----
    {
        id: 'wf-product-manufacturing',
        name: 'Product Manufacturing Run',
        category: 'Manufacturing',
        icon: '🏭',
        description: 'Physical product batch production.',
        steps: [
            { name: 'Raw Material Sourcing', role: 'Manager', days: 3 },
            { name: 'Prototyping', role: 'Engineer', days: 4 },
            { name: 'Production Setup', role: 'Engineer', days: 2 },
            { name: 'Quality Check', role: 'QC', days: 2 },
            { name: 'Packaging', role: 'Manager', days: 2 },
            { name: 'Shipping', role: 'Logistics', days: 2 },
        ],
    },
    {
        id: 'wf-construction',
        name: 'Construction / Interior',
        category: 'Manufacturing',
        icon: '🔨',
        description: 'Home office or interior project.',
        steps: [
            { name: 'Design Blueprint', role: 'Architect', days: 5 },
            { name: 'Material Estimate', role: 'Engineer', days: 2 },
            { name: 'Permits', role: 'Manager', days: 3 },
            { name: 'Foundation', role: 'Contractor', days: 4 },
            { name: 'Structure', role: 'Contractor', days: 5 },
            { name: 'Finishing', role: 'Contractor', days: 4 },
            { name: 'Inspection', role: 'QC', days: 2 },
        ],
    },
    {
        id: 'wf-mechanical-design',
        name: 'Mechanical 3D Design',
        category: 'Manufacturing',
        icon: '⚡',
        description: 'CAD design for mechanical parts.',
        steps: [
            { name: 'Sketches', role: 'Mechanical Engineer', days: 2 },
            { name: '3D Model', role: 'Mechanical Engineer', days: 4 },
            { name: 'Simulation', role: 'Mechanical Engineer', days: 2 },
            { name: 'Iterate', role: 'Mechanical Engineer', days: 2 },
            { name: 'Final CAD', role: 'Mechanical Engineer', days: 1 },
        ],
    },
    {
        id: 'wf-architecture',
        name: 'Architectural Blueprint',
        category: 'Manufacturing',
        icon: '🏛️',
        description: 'Design building blueprints.',
        steps: [
            { name: 'Site Analysis', role: 'Architect', days: 3 },
            { name: 'Concept', role: 'Architect', days: 3 },
            { name: 'Schematic Design', role: 'Architect', days: 4 },
            { name: 'Design Dev', role: 'Architect', days: 5 },
            { name: 'Construction Docs', role: 'Architect', days: 3 },
        ],
    },
];

console.log('Total Workflows:', ALL_WORKFLOWS.length);
